apiVersion: apps/v1
kind: Deployment
metadata:
  name: foldingapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: folding
  template:
    metadata:
      labels:
        app: folding
    spec:
      containers:
      - name: folding
        image: artingu/folding-at-home:latest
        resources:
          limits:
            cpu: "900m"
            memory: "1Gi"
        
